In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
#df=pd.read_csv("/kaggle/input/datasets/rohankayan/years-of-experience-and-salary-dataset/Salary_Data.csv")

In [61]:
df=pd.read_csv("/kaggle/input/datasets/muhammadbinimran/housing-price-prediction-data/housing_price_dataset.csv")

In [62]:
df.head(5)

   SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [63]:
df.shape

(50000, 6)

In [64]:
import matplotlib.pyplot as plt

In [112]:
X=df.iloc[:,0:3]

In [113]:
y=df[["Price"]]

In [114]:

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.33)

In [115]:
from sklearn.linear_model import LinearRegression

In [116]:
lr=LinearRegression()

In [117]:
y_train

               Price
23990  365384.363339
8729    98914.614596
3451   265441.025324
2628   248259.953718
38352  286485.264621
...              ...
11284  324396.846219
44732  319266.944411
38158  248092.662727
860    132414.177622
15795  288751.049986

[33500 rows x 1 columns]

In [118]:
X_test

       SquareFeet  Bedrooms  Bathrooms
33553        1894         5          1
9427         1001         5          3
199          2264         4          3
12447        2299         5          1
39489        2651         2          1
...           ...       ...        ...
27615        2647         2          3
21964        1300         3          3
33321        1181         5          1
40225        2513         2          1
28203        2899         2          3

[16500 rows x 3 columns]

In [119]:
y_test

               Price
33553  170835.035713
9427   126913.469998
199    246611.883092
12447  244250.462969
39489  271127.650112
...              ...
27615  291504.040710
21964  193917.029039
33321  118758.460607
40225  259968.166763
28203  289685.873746

[16500 rows x 1 columns]

In [120]:
X_train

       SquareFeet  Bedrooms  Bathrooms
23990        2561         3          1
8729         1064         5          1
3451         2756         4          2
2628         1731         4          2
38352        2794         5          1
...           ...       ...        ...
11284        2166         5          3
44732        2463         4          1
38158        2812         4          2
860          2188         3          1
15795        2649         5          3

[33500 rows x 3 columns]

In [121]:
lr.fit(X_train,y_train)

LinearRegression()

In [122]:
y_pred=lr.predict(X_test)

In [123]:
lr.coef_

array([[  99.49583218, 5241.77380583, 2999.2680558 ]])

In [124]:
lr.intercept_

array([873.06631322])

In [126]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R² Score: {r2:.2f}")

R² Score: 0.57